package.path = "./?.lua;./?/init.lua;" .. package.path

require("tests/TestUtils")
require("tests/TestAcquisitionLogic")
require("tests/TestBnbFilteringLogic")
require("tests/TestCrdFilteringLogic")
require("tests/TestDataLogic")
require("tests/TestEntrypoint")
require("tests/TestHexFilteringLogic")
require("tests/TestJudgementFilteringLogic")
require("tests/TestJpomFilteringLogic")
require("tests/TestNpcFilteringLogic")
require("tests/TestRarityFirstNBoonsLogic")
require("tests/TestRunStateLogic")
require("tests/TestTraitInfoLogic")
require("tests/TestTraitOfferFilteringLogic")
require("tests/TestTraitOfferFinalizationLogic")
require("tests/TestUiLogic")

local lu = require("luaunit")
os.exit(lu.LuaUnit.run())
