return {
    Enabled = false,
    DebugMode = false,

    ImproveFirstNBoonRarity = 0,
    BridalGlowTargetBoon = "",
    ViewRegion = 4,

    PackedAphroditeTierState = 0,
    PackedApolloTierState = 0,
    PackedAresTierState = 0,
    PackedDemeterTierState = 0,
    PackedHephaestusTierState = 0,
    PackedHeraTierState = 0,
    PackedHestiaTierState = 0,
    PackedPoseidonTierState = 0,
    PackedZeusTierState = 0,

    PackedAphrodite1 = 0, PackedAphrodite2 = 0, PackedAphrodite3 = 0, PackedAphrodite4 = 0, PackedAphrodite5 = 0,
    PackedAphrodite6 = 0, PackedAphrodite7 = 0, PackedAphrodite8 = 0, PackedAphrodite9 = 0, PackedAphrodite10 = 0,
    PackedApollo1 = 0, PackedApollo2 = 0, PackedApollo3 = 0, PackedApollo4 = 0, PackedApollo5 = 0,
    PackedApollo6 = 0, PackedApollo7 = 0, PackedApollo8 = 0, PackedApollo9 = 0, PackedApollo10 = 0,
    PackedAres1 = 0, PackedAres2 = 0, PackedAres3 = 0, PackedAres4 = 0, PackedAres5 = 0,
    PackedAres6 = 0, PackedAres7 = 0, PackedAres8 = 0, PackedAres9 = 0, PackedAres10 = 0,
    PackedDemeter1 = 0, PackedDemeter2 = 0, PackedDemeter3 = 0, PackedDemeter4 = 0, PackedDemeter5 = 0,
    PackedDemeter6 = 0, PackedDemeter7 = 0, PackedDemeter8 = 0, PackedDemeter9 = 0, PackedDemeter10 = 0,
    PackedHephaestus1 = 0, PackedHephaestus2 = 0, PackedHephaestus3 = 0, PackedHephaestus4 = 0, PackedHephaestus5 = 0,
    PackedHephaestus6 = 0, PackedHephaestus7 = 0, PackedHephaestus8 = 0, PackedHephaestus9 = 0, PackedHephaestus10 = 0,
    PackedHera1 = 0, PackedHera2 = 0, PackedHera3 = 0, PackedHera4 = 0, PackedHera5 = 0,
    PackedHera6 = 0, PackedHera7 = 0, PackedHera8 = 0, PackedHera9 = 0, PackedHera10 = 0,
    PackedHestia1 = 0, PackedHestia2 = 0, PackedHestia3 = 0, PackedHestia4 = 0, PackedHestia5 = 0,
    PackedHestia6 = 0, PackedHestia7 = 0, PackedHestia8 = 0, PackedHestia9 = 0, PackedHestia10 = 0,
    PackedPoseidon1 = 0, PackedPoseidon2 = 0, PackedPoseidon3 = 0, PackedPoseidon4 = 0, PackedPoseidon5 = 0,
    PackedPoseidon6 = 0, PackedPoseidon7 = 0, PackedPoseidon8 = 0, PackedPoseidon9 = 0, PackedPoseidon10 = 0,
    PackedZeus1 = 0, PackedZeus2 = 0, PackedZeus3 = 0, PackedZeus4 = 0, PackedZeus5 = 0,
    PackedZeus6 = 0, PackedZeus7 = 0, PackedZeus8 = 0, PackedZeus9 = 0, PackedZeus10 = 0,

    PackedRarityAphrodite = 0,
    PackedRarityApollo = 0,
    PackedRarityAres = 0,
    PackedRarityDemeter = 0,
    PackedRarityHephaestus = 0,
    PackedRarityHera = 0,
    PackedRarityHestia = 0,
    PackedRarityPoseidon = 0,
    PackedRarityZeus = 0,
    PackedRarityArtemis = 0,
    PackedRarityAthena = 0,
    PackedRarityDionysus = 0,
    PackedRarityHermes = 0,

    PackedStaffTierState = 0,
    PackedDaggerTierState = 0,
    PackedAxeTierState = 0,
    PackedTorchTierState = 0,
    PackedLobTierState = 0,
    PackedSuitTierState = 0,

    PackedStaff1 = 0, PackedStaff2 = 0, PackedStaff3 = 0, PackedStaff4 = 0, PackedStaff5 = 0,
    PackedDagger1 = 0, PackedDagger2 = 0, PackedDagger3 = 0, PackedDagger4 = 0, PackedDagger5 = 0,
    PackedAxe1 = 0, PackedAxe2 = 0, PackedAxe3 = 0, PackedAxe4 = 0, PackedAxe5 = 0,
    PackedTorch1 = 0, PackedTorch2 = 0, PackedTorch3 = 0, PackedTorch4 = 0, PackedTorch5 = 0,
    PackedLob1 = 0, PackedLob2 = 0, PackedLob3 = 0, PackedLob4 = 0, PackedLob5 = 0,
    PackedSuit1 = 0, PackedSuit2 = 0, PackedSuit3 = 0, PackedSuit4 = 0, PackedSuit5 = 0,

    PackedHermesTierState = 0,
    PackedHermes1 = 0, PackedHermes2 = 0, PackedHermes3 = 0, PackedHermes4 = 0, PackedHermes5 = 0,

    PackedChaosBuff = 0,
    PackedChaosCurse = 0,
    PackedArtemis = 0,
    PackedAthena = 0,
    PackedSelene = 0,

    PackedArachne = 0,
    PackedNarcissus = 0,
    PackedEcho = 0,
    PackedHades = 0,
    PackedMedea = 0,
    PackedCirce = 0,
    PackedIcarus = 0,
    PackedDionysus = 0,

    PackedHadesKeepsake = 0,
    PackedCirceBNB = 0,
    PackedCirceCRD = 0,
    PackedJudgement1 = 0,
    PackedJudgement2 = 0,
    PackedJudgement3 = 0,
}
